#
# Don't change this file. Copy this file as Makefile.mine and then set the 
# variables. The Makefile.mine will be included by the root Makefile, but 
# ignored by git.
#

###############################################################################
# Scheduler type:
# - rm: Rate Monotonic
# - edf: Earliest Deadline First
# - dp: Dual Priority
# - ss: Slack Stealing
#
HST_SCHED ?= rm

###############################################################################
# FreeRTOS version supported.
# - v8.2.1
# - v9.0.0
FREERTOS_VERSION ?= v9.0.0

###############################################################################
# Supported boards for the examples:
# - lpc1768
# - nucleo_f411re
# - nucleo_f103rb
# - STM32F4DISCOVERY
BOARD ?= lpc1768
