# This file was automagically generated by mbed.org. For more information, 
# see http://mbed.org/handbook/Exporting-to-GCC-ARM-Embedded

#
# Modify example to build in Makefile.mine. 
#
-include Makefile.mine

MBED_LIB_PATH = ./mbed/$(BOARD)
BIN_DIR = ./build

###############################################################################
PROJECT = hst

FREERTOS_OBJECTS += ./FreeRTOS/$(FREERTOS_VERSION)/tasks.o
FREERTOS_OBJECTS += ./FreeRTOS/$(FREERTOS_VERSION)/queue.o
FREERTOS_OBJECTS += ./FreeRTOS/$(FREERTOS_VERSION)/list.o
FREERTOS_OBJECTS += ./FreeRTOS/$(FREERTOS_VERSION)/portable/MemMang/heap_1.o
ifeq ($(BOARD), lpc1768)
FREERTOS_OBJECTS += ./FreeRTOS/$(FREERTOS_VERSION)/portable/GCC/ARM_CM3/port.o
endif
ifeq ($(BOARD), nucleo_f103rb)
FREERTOS_OBJECTS += ./FreeRTOS/$(FREERTOS_VERSION)/portable/GCC/ARM_CM3/port.o
endif
ifeq ($(BOARD), nucleo_f411re)
FREERTOS_OBJECTS += ./FreeRTOS/$(FREERTOS_VERSION)/portable/GCC/ARM_CM4F/port.o
endif

HST_OBJECTS += ./hst/$(HST_SCHED)/scheduler_logic_$(HST_SCHED).o 
HST_OBJECTS += ./hst/scheduler.o
HST_OBJECTS += ./hst/wcrt.o
ifeq ($(HST_SCHED), ss)
HST_OBJECTS += ./hst/$(HST_SCHED)/slack.o
endif

EXAMPLE_OBJECTS += ./examples/$(HST_SCHED)/main.o 
EXAMPLE_OBJECTS += ./examples/utils/utils.o

OBJECTS = $(FREERTOS_OBJECTS) $(HST_OBJECTS) $(EXAMPLE_OBJECTS)

FREERTOS_INCLUDE_PATHS += -I../FreeRTOS/$(FREERTOS_VERSION)/config
FREERTOS_INCLUDE_PATHS += -I../FreeRTOS/$(FREERTOS_VERSION)/include
ifeq ($(BOARD), lpc1768)
FREERTOS_INCLUDE_PATHS += -I../FreeRTOS/$(FREERTOS_VERSION)/portable/GCC/ARM_CM3
endif
ifeq ($(BOARD), nucleo_f103rb)
FREERTOS_INCLUDE_PATHS += -I../FreeRTOS/$(FREERTOS_VERSION)/portable/GCC/ARM_CM3
endif
ifeq ($(BOARD), nucleo_f411re)
FREERTOS_INCLUDE_PATHS += -I../FreeRTOS/$(FREERTOS_VERSION)/portable/GCC/ARM_CM4F
endif
HST_INCLUDE_PATHS += -I../hst 
HST_INCLUDE_PATHS += -I../hst/$(HST_SCHED)
EXAMPLE_INCLUDE_PATHS = -I../examples/utils

############################################################################### 
GCC_BIN = 
AS      = $(GCC_BIN)arm-none-eabi-as
CC      = $(GCC_BIN)arm-none-eabi-gcc
CPP     = $(GCC_BIN)arm-none-eabi-g++
LD      = $(GCC_BIN)arm-none-eabi-gcc
OBJCOPY = $(GCC_BIN)arm-none-eabi-objcopy
OBJDUMP = $(GCC_BIN)arm-none-eabi-objdump
SIZE 	= $(GCC_BIN)arm-none-eabi-size

export AS CC CPP LD OBJCOPY SIZE BIN_DIR MBED_LIB_PATH PROJECT FREERTOS_VERSION FREERTOS_OBJECTS HST_OBJECTS EXAMPLE_OBJECTS OBJECTS FREERTOS_INCLUDE_PATHS HST_INCLUDE_PATHS EXAMPLE_INCLUDE_PATHS

all: $(BOARD)

$(BOARD):
	+@echo "Target board: $(BOARD)"
	@$(MAKE) -f Makefile_$(BOARD).mk
	
clean:
	@echo "Target board: lpc1768"
	@$(MAKE) -f Makefile_$(BOARD).mk clean
